src/Entity/Expose.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExposeRepository")
 */
class Expose
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}wildcircus{% endblock %}

{% block body %}
<!-- home part -->
<div class="box_home">
    {% for home in home %}
        <div class="home">
            <h1>{{ home.title }}</h1>
            <p>{{ home.paragraph }}</p>
            <img class="home_picture"
            src="../images/{{ home.image }}"
            alt="Grapefruit slice atop a pile of other slices">
        </div>
    {% endfor %}
</div>
<!-- list artist generated by loop part -->
<div class="box_artist">
    {% for artist in artist %}
        <div class="artist">
            <h1>{{ artist.name }}</h1>
            <p>{{ artist.description }}</p>
            <img class="home_picture"
            src="../images/{{ artist.image }}"
            alt="Grapefruit slice atop a pile of other slices">
        </div>
    {% endfor %}
</div>
<!-- show generated by loop -->
<div class="box_show">
    {% for expose in expose %}
        <div class="show">
            <h1>{{ expose.name }}</h1>
            <p>{{ expose.description }}</p>
            <img class="home_picture"
                src="../images/{{ expose.image }}"
                alt="Grapefruit slice atop a pile of other slices">
        </div>
    {% endfor %}
</div>
<!-- Contact part -->
<div>    
    <div>
        <label for="name">Nom :</label>
        <input type="text" id="name" name="user_name" />
    </div>
    <div>
        <label for="email">E-mail :</label>
        <input type="email" id="mail" name="user_email" />
    </div>
    <div>
        <label for="message">Message:</label>
        <textarea id="message" name="user_message"></textarea>
    </div>
    <div class="button">
        <button type="submit">Send</button>
    </div>
</div>

{% endblock %}